# Generated by Django 3.0.8 on 2020-08-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='media/default_avatar.png', upload_to=''),
        ),
    ]
